server.port: 9090
security.jwt.token:
  secret-key: very-long-secret-key-to-avoid-problems-with-jwt-security-lib
  expire-length: 3600000 #one hour

logging:
  level:
    root: INFO
    com.netcracker: TRACE

spring.datasource:
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  url: jdbc:postgresql://localhost:5432/folktaxi
  username: postgres
  password: root

security:
  oauth2:
    client:
      client-id: cliente
      client-secret: password
      scope: read,write
      auto-approve-scopes: '.*'

servicesmgmt:
  authorities: uaa.resource,oauth.service,clients.read,clients.write,clients.secret
  authorized-grant-types: authorization_code,client_credentials,password,implicit
  autoapprove: true
  override: true
  redirect-uri: http://servicesmgmt.10.244.0.34.xip.io/auth/cloudfoundry/callback
  scope: openid,cloud_controller.read,cloud_controller.write
  secret: servicesmgmt-secret

