server.port:

logging:
  level:
    root: INFO
    com.netcracker: TRACE

spring.datasource:
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  url: jdbc:postgresql://localhost:5432/folktaxi
  username:
  password: 
